version: '2'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    volumes:
      - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - powerdns

  powerdns:
    build: ./powerdns
    ports:
      - 8081:8081
    environment:
      - PDNS_LOG_LEVEL=0
      - PDNS_API_KEY=MCv2XyZ2nFxPZxAxdosBxBWcVe32
      - PDNS_WEBSERVER_PASSWORD=tiY6H5vXCFhUTM
      - PDNS_WEBSERVER_ALLOWED_FROM=0.0.0.0/0
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
