version: '2'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    volumes:
      - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-data/proxy:/etc/nginx/sites-enabled/proxy
    depends_on:
      - powerdns

  powerdns:
    build: ./powerdns
    ports:
      - 1053:53/udp
      - 1053:53/tcp
      - 8081:8081
    environment:
      - PDNS_LOG_LEVEL=0
      - PDNS_API_KEY=34H5G34J5H43H34
      - PDNS_WEBSERVER_PASSWORD=123456
      - PDNS_WEBSERVER_ALLOWED_FROM=127.0.0.1,::1,10.0.0.0/8
    volumes: 
      - ./powerdns-data/:/pdns/
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
